=== kcwiakalski/keycloak-manager/config-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "clientDefinition": {
            "type": "object",
            "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_clientrepresentation"
        },
        "groups": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_grouprepresentation"
            }
        },
        "roles": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/#_rolerepresentation"
            }
        },
        "scopes": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_clientscoperepresentation"
            }
        },
        "resources": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_resourcerepresentation"
            }
        },
        "policies": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_policyrepresentation"
            }
        },
        "permissions": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_policyrepresentation"
            }
        }
    }
}

=== kcwiakalski/keycloak-manager/product-service-sec-conf.json
{
    "clientDefinition": {
        "enabled": true,
        "redirectUris": [
            "*"
        ],
        "clientId": "product-catalog",
        "protocol": "openid-connect",
        "attributes": {
            "login_theme": "base"
        },
        "authorizationServicesEnabled": true,
        "serviceAccountsEnabled": true,
        "publicClient": false
    },
    "scopes": [
        {
            "name": "configuration.attributes.manage",
            "displayName": "Allows management operations on attirbute definitions"
        },
        {
            "name": "configuration.attributes.view",
            "displayName": "Allows viewing attributes defined in system"
        },
        {
            "name": "configuration.category.manage",
            "displayName": "Allows management operations on categories (CRUD-like)"
        },
        {
            "name": "configuration.category.view",
            "displayName": "Allows viewing categories defined in the system"
        },
        {
            "name": "canonical.product.configure",
            "displayName": "Allows advanced product configuration (e.g. category, differentation attirbtues etc)"
        },
        {
            "name": "canonical.product.modify",
            "displayName": "Allows modification of product data"
        },
        {
            "name": "canonical.product.view",
            "displayName": "Allows viewing of canonical data for product"
        },
        {
            "name": "dictionary.view",
            "displayName": "Allows viewing content of dictionaries defined in system"
        },
        {
            "name": "product.view",
            "displayName": "Gives access to published product data"
        },
        {
            "name": "tasks.publish.data",
            "displayName": "Allows publication of product data"
        },
        {
            "name": "tasks.finish",
            "displayName": "Allows completion of tasks defined for products"
        },
        {
            "name": "tasks.view",
            "displayName": "Gives access to tasks defined for products"
        },
        {
            "name": "tasks.manage",
            "displayName": "Allows for task management operations"
        },
        {
            "name": "user.view",
            "displayName": "Gives access to users defined in the system"
        }
    ],
    "resources": [
        {
            "name": "tasks",
            "displayName": "Task management resource",
            "scopes": [
                {
                    "name": "tasks.publish.data"
                },
                {
                    "name": "tasks.finish"
                },
                {
                    "name": "tasks.view"
                },
                {
                    "name": "tasks.manage"
                },
                {
                    "name": "user.view"
                }
            ]
        },
        {
            "name": "system-configuration",
            "displayName": "System configuration management",
            "scopes": [
                {
                    "name": "configuration.attributes.manage"
                },
                {
                    "name": "configuration.attributes.view"
                },
                {
                    "name": "configuration.category.manage"
                },
                {
                    "name": "configuration.category.view"
                },
                {
                    "name": "dictionary.view"
                },
                {
                    "name": "user.view"
                }
            ]
        },
        {
            "name": "product-data",
            "displayName": "Product data management and distribution",
            "scopes": [
                {
                    "name": "canonical.product.configure"
                },
                {
                    "name": "canonical.product.modify"
                },
                {
                    "name": "canonical.product.view"
                },
                {
                    "name": "product.view"
                }
            ]
        }
    ],
    "policies": [
        {
            "name": "is_system_admin",
            "type": "group",
            "description": "Policy detecting if user is system administrator, giving him total control over system configuration",
            "groups": [
                {
                    "path": "/employee-standard/employee-data-admin/employee-system-admin",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_data_admin",
            "type": "group",
            "description": "Policy detecting if user can perform advanced management of product data",
            "groups": [
                {
                    "path": "/employee-standard/employee-data-admin",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_standard_employee",
            "type": "group",
            "description": "Policy detecting regular system users that can manage product data",
            "groups": [
                {
                    "path": "/employee-standard",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_task_manager",
            "type": "group",
            "description": "Policy detecting product-related tasks managers, giving them control over advanced tasks",
            "groups": [
                {
                    "path": "/task-manager",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_external_user",
            "type": "group",
            "description": "Policy detecting persons for outside of the Product Catalog organization",
            "groups": [
                {
                    "path": "/external-user",
                    "extendChildren": true
                }
            ]
        }
    ],
    "permissions": [
        {
            "name": "tasks-advanced-management",
            "description": "Gives control over all product-related tasks",
            "type": "scope",
            "resources": [
                "tasks"
            ],
            "scopes": [
                "tasks.finish"
            ],
            "policies": [
                "is_task_manager"
            ]
        },
        {
            "name": "product-publication",
            "description": "Allows to publish product data and complete publication tasks",
            "type": "scope",
            "resources": [
                "tasks"
            ],
            "scopes": [
                "tasks.publish.data"
            ],
            "policies": [
                "is_data_admin"
            ]
        },
        {
            "name": "tasks-basic-operations",
            "description": "Allows to work on tasks",
            "type": "scope",
            "resources": [
                "tasks"
            ],
            "scopes": [
                "tasks.manage",
                "tasks.view"
            ],
            "policies": [
                "is_standard_employee"
            ]
        },
        {
            "name": "config-data-basic",
            "description": "Gives access to common configuration data",
            "type": "scope",
            "resources": [
                "system-configuration"
            ],
            "scopes": [
                "configuration.category.view",
                "dictionary.view",
                "user.view"
            ],
            "policies": [
                "is_standard_employee"
            ]
        },
        {
            "name": "advanced-system-config",
            "description": "Gives access to advanced system configuration like categories, attributes etc",
            "type": "scope",
            "resources": [
                "system-configuration"
            ],
            "scopes": [
                "configuration.attributes.manage",
                "configuration.attributes.view",
                "configuration.category.manage"
            ],
            "policies": [
                "is_system_admin"
            ]
        },
        {
            "name": "product-view-access",
            "description": "Allows to view data about published products",
            "type": "scope",
            "decisionStrategy": "AFFIRMATIVE",
            "resources": [
                "product-data"
            ],
            "scopes": [
                "product.view"
            ],
            "policies": [
                "is_external_user",
                "is_standard_employee"
            ]
        },
        {
            "name": "product-data-management",
            "description": "Allows to modify canonical data in product cards",
            "type": "scope",
            "resources": [
                "product-data"
            ],
            "scopes": [
                "canonical.product.configure",
                "canonical.product.modify",
                "canonical.product.view"
            ],
            "policies": [
                "is_standard_employee"
            ]
        }
    ]
}

=== kcwiakalski/keycloak-manager/examples/data-access-client-deletion.json
{
    "clientDefinition": {
        "enabled": true,
        "redirectUris": [
            "*"
        ],
        "clientId": "sample-client",
        "protocol": "openid-connect",
        "attributes": {
            "login_theme": "base"
        },
        "authorizationServicesEnabled": true,
        "serviceAccountsEnabled": true,
        "publicClient": false
    },
    "groups": [
        {
            "name": "data-user",
            "path": "/data-user"
        },
        {
            "name": "data-creator",
            "path": "/data-user/data-creator"
        },
        {
            "name": "sysadmin",
            "path": "/sysadmin"
        }
    ],
    "scopes": [
        {
            "name": "read.all",
            "displayName": "Allows read all data"
        },
        {
            "name": "write.all",
            "displayName": "Allows writing all data"
        },
        {
            "name": "manage.config",
            "displayName": "Allows management of system configuration"
        },
        {
            "displayName": "New fancy scope",
            "name": "fancy.scope"
        }
    ],
    "resources": [
        {
            "name": "data",
            "displayName": "Data access resource",
            "scopes": [
                {
                    "name": "read.all"
                },
                {
                    "name": "write.all"
                }
            ]
        },
        {
            "name": "system-configuration",
            "displayName": "System configuration management",
            "scopes": [
                {
                    "name": "manage.config"
                }
            ]
        },
        {
            "name": "fancy-new-resource",
            "displayName": "Completly new resource",
            "scopes": [
                {
                    "name": "fancy.scope"
                }
            ]
        }
    ],
    "policies": [
        {
            "name": "is_system_admin",
            "type": "group",
            "description": "Policy detecting if user is system administrator, giving him total control over system configuration",
            "groups": [
                {
                    "path": "/sysadmin",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_data_user",
            "type": "group",
            "description": "Policy detecting if user can read data",
            "groups": [
                {
                    "path": "/data-user",
                    "extendChildren": true
                }
            ]
        },
        {
            "name": "is_data_provider",
            "type": "group",
            "description": "Policy detecting if user can create data",
            "groups": [
                {
                    "path": "/data-user/data-creator",
                    "extendChildren": true
                }
            ]
        }
    ],
    "permissions": [
        {
            "name": "data-read-permission",
            "description": "Allows to access data in the system",
            "type": "scope",
            "resources": [
                "data"
            ],
            "scopes": [
                "read.all"
            ],
            "policies": [
                "is_data_user"
            ]
        },
        {
            "name": "create-data-permission",
            "description": "Allows to create data in the system",
            "type": "scope",
            "resources": [
                "data"
            ],
            "scopes": [
                "write.all"
            ],
            "policies": [
                "is_data_provider"
            ]
        }
    ]
}
